//! The JSON field maps of vpinball's VPZ writer, with the value type its
//! save code writes each field with.
//!
//! Generated from vpinball 13c4f8f83: `src/utils/JSONSerializer.cpp` (names, in
//! declaration order, shared part fields first) and the `Write*` calls of
//! the object `Save` methods (types), the shared part fields of
//! `IEditable::SaveSharedEditableFields` only for parts. `None` marks a
//! field vpinball only reads, from older files, and never writes.

use super::{Field, Node, Value};

/// eItemSurface (item type 0)
pub(super) const ITEM_0: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("CLDW", "collidable", Some(Value::Bool)),
    Field::new("DILB", "disable_lighting_below", Some(Value::Float)),
    Field::new("DILI", "disable_lighting_legacy", None),
    Field::new("DILT", "disable_lighting_top", Some(Value::Float)),
    Field::new("DROP", "droppable", Some(Value::Bool)),
    Field::new("DSPT", "ui_show_texture", Some(Value::Bool)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("FLIP", "flipbook", Some(Value::Bool)),
    Field::new("HTBT", "height_bottom", Some(Value::Float)),
    Field::new("HTEV", "hitEvent", Some(Value::Bool)),
    Field::new("HTTP", "height_top", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("INNR", "inner", Some(Value::Bool)),
    Field::new("ISBS", "is_bottom_solid", Some(Value::Bool)),
    Field::new("MAPH", "physics_material", Some(Value::String)),
    Field::new("OVPH", "overwrite_physics", Some(Value::Bool)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("SIMA", "side_material", Some(Value::String)),
    Field::new("SIMG", "side_image", Some(Value::String)),
    Field::new("SLGA", "slingshot_animation", Some(Value::Bool)),
    Field::new("SLGF", "slingshot_force", Some(Value::Float)),
    Field::new("SLMA", "sling_shot_material", Some(Value::String)),
    Field::new("SLTH", "slingshot_threshold", Some(Value::Float)),
    Field::new("SVBL", "side_visible", Some(Value::Bool)),
    Field::new("THRS", "threshold", Some(Value::Float)),
    Field::new("TOMA", "top_material", Some(Value::String)),
    Field::new("VSBL", "visible", Some(Value::Bool)),
    Field::new("WFCT", "friction", Some(Value::Float)),
    Field::new("WSCT", "scatter", Some(Value::Float)),
];

/// eItemFlipper (item type 1)
pub(super) const ITEM_1: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ANGE", "end_angle", Some(Value::Float)),
    Field::new("ANGS", "start_angle", Some(Value::Float)),
    Field::new("BASR", "base_radius", Some(Value::Float)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("ENBL", "enabled", Some(Value::Bool)),
    Field::new("ENDR", "end_radius", Some(Value::Float)),
    Field::new("FHGT", "height", Some(Value::Float)),
    Field::new("FLPR", "flipper_radius_max", Some(Value::Float)),
    Field::new("FORC", "mass", Some(Value::Float)),
    Field::new("FRIC", "friction", Some(Value::Float)),
    Field::new("FRMN", "flipper_radius_min", Some(Value::Float)),
    Field::new("FRTN", "return", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("OVRP", "override_physics", Some(Value::Int)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RHGF", "rubber_height", Some(Value::Float)),
    Field::new("RHGT", "rubber_height_legacy", Some(Value::Int)),
    Field::new("RPUP", "ramp_up", Some(Value::Float)),
    Field::new("RTHF", "rubber_thickness", Some(Value::Float)),
    Field::new("RTHK", "rubber_thickness_legacy", Some(Value::Int)),
    Field::new("RUMA", "rubber_material", Some(Value::String)),
    Field::new("RWDF", "rubber_width", Some(Value::Float)),
    Field::new("RWDT", "rubber_width_legacy", Some(Value::Int)),
    Field::new("SCTR", "scatter", Some(Value::Float)),
    Field::new("STRG", "strength", Some(Value::Float)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TDAA", "torque_damping_angle", Some(Value::Float)),
    Field::new("TODA", "torque_damping", Some(Value::Float)),
    Field::new("VSBL", "visible", Some(Value::Bool)),
];

/// eItemTimer (item type 2)
pub(super) const ITEM_2: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BGLS", "desktop_backdrop", Some(Value::Bool)),
];

/// eItemPlunger (item type 3)
pub(super) const ITEM_3: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ANFR", "anim_frames", Some(Value::Int)),
    Field::new("APLG", "auto_plunger", Some(Value::Bool)),
    Field::new("HIGH", "height", Some(Value::Float)),
    Field::new("HPSL", "stroke", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("MECH", "mech_plunger", Some(Value::Bool)),
    Field::new("MEST", "mech_strength", Some(Value::Float)),
    Field::new("MOMX", "momentum_transfer", Some(Value::Float)),
    Field::new("MPRK", "park_position", Some(Value::Float)),
    Field::new("PSCV", "scatter_velocity", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RNGD", "ring_diam", Some(Value::Float)),
    Field::new("RNGG", "ring_gap", Some(Value::Float)),
    Field::new("RNGW", "ring_width", Some(Value::Float)),
    Field::new("RODD", "rod_diam", Some(Value::Float)),
    Field::new("SPDF", "speed_fire", Some(Value::Float)),
    Field::new("SPDP", "speed_pull", Some(Value::Float)),
    Field::new("SPRD", "spring_diam", Some(Value::Float)),
    Field::new("SPRE", "spring_end_loops", Some(Value::Float)),
    Field::new("SPRG", "spring_gauge", Some(Value::Float)),
    Field::new("SPRL", "spring_loops", Some(Value::Float)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TIPS", "tip_shape", Some(Value::String)),
    Field::new("TYPE", "type", Some(Value::Int)),
    Field::new("VSBL", "visible", Some(Value::Bool)),
    Field::new("WDTH", "width", Some(Value::Float)),
    Field::new("ZADJ", "z_adjust", Some(Value::Float)),
];

/// eItemTextbox (item type 4)
pub(super) const ITEM_4: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ALGN", "alignment", Some(Value::Int)),
    Field::new("CLRB", "back_color", Some(Value::Int)),
    Field::new("CLRF", "font_color", Some(Value::Int)),
    Field::new("FONT", "font", Some(Value::Font)),
    Field::new("IDMD", "dmd", Some(Value::Bool)),
    Field::new("INSC", "intensity_scale", Some(Value::Float)),
    Field::new("TEXT", "text", Some(Value::String)),
    Field::new("TRNS", "transparent", Some(Value::Bool)),
    Field::new("VER1", "v1", Some(Value::Vector2)),
    Field::new("VER2", "v2", Some(Value::Vector2)),
];

/// eItemBumper (item type 5)
pub(super) const ITEM_5: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BAMA", "base_material", Some(Value::String)),
    Field::new("BSCT", "scatter", Some(Value::Float)),
    Field::new("BSVS", "base_visible", Some(Value::Bool)),
    Field::new("BVIS", "all_visible", None),
    Field::new("CAVI", "cap_visible", Some(Value::Bool)),
    Field::new("COLI", "collidable", Some(Value::Bool)),
    Field::new("FORC", "force", Some(Value::Float)),
    Field::new("HAHE", "hit_event", Some(Value::Bool)),
    Field::new("HISC", "height_scale", Some(Value::Float)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("ORIN", "orientation", Some(Value::Float)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("RDLI", "ring_drop_offset", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RIMA", "ring_material", Some(Value::String)),
    Field::new("RISP", "ring_speed", Some(Value::Float)),
    Field::new("RIVS", "ring_visible", Some(Value::Bool)),
    Field::new("SKMA", "skirt_material", Some(Value::String)),
    Field::new("SKVS", "skirt_visible", Some(Value::Bool)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("THRS", "threshold", Some(Value::Float)),
];

/// eItemTrigger (item type 6)
pub(super) const ITEM_6: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ANSP", "anim_speed", Some(Value::Float)),
    Field::new("EBLD", "enabled", Some(Value::Bool)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("ROTA", "rotation", Some(Value::Float)),
    Field::new("SCAX", "scale_x", Some(Value::Float)),
    Field::new("SCAY", "scale_y", Some(Value::Float)),
    Field::new("SHAP", "shape", Some(Value::Int)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("THOT", "hit_height", Some(Value::Float)),
    Field::new("VSBL", "visible", Some(Value::Bool)),
    Field::new("WITI", "wire_thickness", Some(Value::Float)),
];

/// eItemLight (item type 7)
pub(super) const ITEM_7: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BGLS", "desktop_backdrop", Some(Value::Bool)),
    Field::new("BHHI", "bulb_halo_height", Some(Value::Float)),
    Field::new("BINT", "blink_interval", Some(Value::Int)),
    Field::new("BMSC", "mesh_radius", Some(Value::Float)),
    Field::new("BMVA", "modulate_vs_add", Some(Value::Float)),
    Field::new("BPAT", "blink_pattern", Some(Value::String)),
    Field::new("BULT", "bulb_light", Some(Value::Bool)),
    Field::new("BWTH", "intensity", Some(Value::Float)),
    Field::new("COL2", "color2", Some(Value::Int)),
    Field::new("COLR", "color", Some(Value::Int)),
    Field::new("FADE", "fader", Some(Value::Int)),
    Field::new("FAPO", "falloff_power", Some(Value::Float)),
    Field::new("FASD", "fade_speed_down", Some(Value::Float)),
    Field::new("FASP", "fade_speed_up", Some(Value::Float)),
    Field::new("HGHT", "height", Some(Value::Float)),
    Field::new("IMG1", "image", Some(Value::String)),
    Field::new("IMMO", "image_mode", Some(Value::Bool)),
    Field::new("LIDB", "depth_bias", Some(Value::Float)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("SHAP", "shape", None),
    Field::new("SHBM", "show_bulb_mesh", Some(Value::Bool)),
    Field::new("SHDW", "shadows", Some(Value::Int)),
    Field::new("SHRB", "show_reflection_on_ball", Some(Value::Bool)),
    Field::new("STAT", "state_legacy", Some(Value::Int)),
    Field::new("STBM", "static_bulb_mesh", Some(Value::Bool)),
    Field::new("STTF", "state", Some(Value::Float)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TRMS", "transmission_scale", Some(Value::Float)),
    Field::new("VSBL", "visible", Some(Value::Bool)),
];

/// eItemKicker (item type 8)
pub(super) const ITEM_8: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("EBLD", "enabled", Some(Value::Bool)),
    Field::new("FATH", "fall_through", Some(Value::Bool)),
    Field::new("KHAC", "hit_accuracy", Some(Value::Float)),
    Field::new("KHHI", "hit_height", Some(Value::Float)),
    Field::new("KORI", "orientation", Some(Value::Float)),
    Field::new("KSCT", "scatter", Some(Value::Float)),
    Field::new("LEMO", "legacy_mode", Some(Value::Bool)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TYPE", "type", Some(Value::Int)),
];

/// eItemDecal (item type 9)
pub(super) const ITEM_9: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BGLS", "desktop_backdrop", Some(Value::Bool)),
    Field::new("COLR", "color", Some(Value::Int)),
    Field::new("FONT", "font", Some(Value::Font)),
    Field::new("HIGH", "height", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("ROTA", "rotation", Some(Value::Float)),
    Field::new("SIZE", "sizing_type", Some(Value::Int)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TEXT", "text", Some(Value::String)),
    Field::new("TYPE", "type", Some(Value::Int)),
    Field::new("VERT", "vertical_text", Some(Value::Bool)),
    Field::new("WDTH", "width", Some(Value::Float)),
];

/// eItemGate (item type 10)
pub(super) const ITEM_10: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("AFRC", "damping", Some(Value::Float)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("GAMA", "angle_max", Some(Value::Float)),
    Field::new("GAMI", "angle_min", Some(Value::Float)),
    Field::new("GATY", "type", Some(Value::Int)),
    Field::new("GCOL", "collidable", Some(Value::Bool)),
    Field::new("GFRC", "friction", Some(Value::Float)),
    Field::new("GGFC", "gravity_factor", Some(Value::Float)),
    Field::new("GSUP", "show_bracket", Some(Value::Bool)),
    Field::new("GVSB", "visible", Some(Value::Bool)),
    Field::new("HGTH", "height", Some(Value::Float)),
    Field::new("LGTH", "length", Some(Value::Float)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("ROTA", "rotation", Some(Value::Float)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("TWWA", "two_way", Some(Value::Bool)),
];

/// eItemSpinner (item type 11)
pub(super) const ITEM_11: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("AFRC", "damping", Some(Value::Float)),
    Field::new("HIGH", "height", Some(Value::Float)),
    Field::new("IMGF", "image", Some(Value::String)),
    Field::new("LGTH", "length", Some(Value::Float)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("ROTA", "rotation", Some(Value::Float)),
    Field::new("SELA", "elasticity", Some(Value::Float)),
    Field::new("SMAX", "angle_max", Some(Value::Float)),
    Field::new("SMIN", "angle_min", Some(Value::Float)),
    Field::new("SSUP", "show_bracket", Some(Value::Bool)),
    Field::new("SURF", "surface", Some(Value::String)),
    Field::new("SVIS", "visible", Some(Value::Bool)),
];

/// eItemRamp (item type 12)
pub(super) const ITEM_12: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ALGN", "alignment", Some(Value::Int)),
    Field::new("CLDR", "collidable", Some(Value::Bool)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("HTBT", "height_bottom", Some(Value::Float)),
    Field::new("HTEV", "hitEvent", Some(Value::Bool)),
    Field::new("HTTP", "height_top", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("IMGW", "image_walls", Some(Value::Bool)),
    Field::new("MAPH", "physics_material", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("OVPH", "overwrite_physics", Some(Value::Bool)),
    Field::new("RADB", "depth_bias", Some(Value::Float)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("RADX", "wire_distance_x", Some(Value::Float)),
    Field::new("RADY", "wire_distance_y", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RFCT", "friction", Some(Value::Float)),
    Field::new("RSCT", "scatter", Some(Value::Float)),
    Field::new("RVIS", "visible", Some(Value::Bool)),
    Field::new("THRS", "threshold", Some(Value::Float)),
    Field::new("TYPE", "type", Some(Value::Int)),
    Field::new("WDBT", "width_bottom", Some(Value::Float)),
    Field::new("WDTP", "width_top", Some(Value::Float)),
    Field::new("WLHL", "left_wall_height", Some(Value::Float)),
    Field::new("WLHR", "right_wall_height", Some(Value::Float)),
    Field::new("WVHL", "left_wall_height_visible", Some(Value::Float)),
    Field::new("WVHR", "right_wall_height_visible", Some(Value::Float)),
];

/// eItemDispReel (item type 17)
pub(super) const ITEM_17: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("CLRB", "back_color", Some(Value::Int)),
    Field::new("FONT", "font", None),
    Field::new("GIPR", "images_per_grid_row", Some(Value::Int)),
    Field::new("HIGH", "height", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MSTP", "motor_steps", Some(Value::Float)),
    Field::new("RANG", "digit_range", Some(Value::Float)),
    Field::new("RCNT", "reel_count", Some(Value::Float)),
    Field::new("RSPC", "reel_spacing", Some(Value::Float)),
    Field::new("SOUN", "sound", Some(Value::String)),
    Field::new("TRNS", "transparent", Some(Value::Bool)),
    Field::new("UGRD", "use_image_grid", Some(Value::Bool)),
    Field::new("UPTM", "update_interval", Some(Value::Int)),
    Field::new("VER1", "v1", Some(Value::Vector2)),
    Field::new("VER2", "v2", Some(Value::Vector2)),
    Field::new("VISI", "visible", Some(Value::Bool)),
    Field::new("WDTH", "width", Some(Value::Float)),
];

/// eItemLightSeq (item type 18)
pub(super) const ITEM_18: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BGLS", "desktop_backdrop", Some(Value::Bool)),
    Field::new("COLC", "collection", Some(Value::WideString)),
    Field::new("CTRX", "center_x", Some(Value::Float)),
    Field::new("CTRY", "center_y", Some(Value::Float)),
    Field::new("UPTM", "update_interval", Some(Value::Int)),
];

/// eItemPrimitive (item type 19)
pub(super) const ITEM_19: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ADDB", "add_blend", Some(Value::Bool)),
    Field::new("CLDR", "collidable", Some(Value::Bool)),
    Field::new("COLR", "color", Some(Value::Int)),
    Field::new("CORF", "collision_reduction_factor", Some(Value::Float)),
    Field::new("DILB", "disable_lighting_below", Some(Value::Float)),
    Field::new("DILI", "disable_lighting_legacy", None),
    Field::new("DILT", "disable_lighting_top", Some(Value::Float)),
    Field::new("DIPT", "display_texture", Some(Value::Bool)),
    Field::new("DTXI", "draw_textures_inside", Some(Value::Bool)),
    Field::new("EBFC", "backfaces_enabled", Some(Value::Bool)),
    Field::new("EFUI", "ui_edge_factor", Some(Value::Float)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("FALP", "alpha", Some(Value::Float)),
    Field::new("HTEV", "hitEvent", Some(Value::Bool)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("ISTO", "toy", Some(Value::Bool)),
    Field::new("LMAP", "lightmap", Some(Value::String)),
    Field::new("M3DN", "mesh_file", Some(Value::String)),
    Field::new("MAPH", "physics_material", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("NRMA", "normal_map", Some(Value::String)),
    Field::new("OSNM", "object_space_normal_map", Some(Value::Bool)),
    Field::new("OVPH", "overwrite_physics", Some(Value::Bool)),
    Field::new("PIDB", "depth_bias", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("REFL", "reflection_probe", Some(Value::String)),
    Field::new("REFR", "refraction_probe", Some(Value::String)),
    Field::new("RFCT", "friction", Some(Value::Float)),
    Field::new("RSCT", "scatter", Some(Value::Float)),
    Field::new("RSTR", "reflection_strength", Some(Value::Float)),
    Field::new("RTHI", "refraction_thickness", Some(Value::Float)),
    Field::new("RTV0", "prim_rot1_x", Some(Value::Float)),
    Field::new("RTV1", "prim_rot1_y", Some(Value::Float)),
    Field::new("RTV2", "prim_rot1_z", Some(Value::Float)),
    Field::new("RTV3", "prim_trans_x", Some(Value::Float)),
    Field::new("RTV4", "prim_trans_y", Some(Value::Float)),
    Field::new("RTV5", "prim_trans_z", Some(Value::Float)),
    Field::new("RTV6", "prim_rot2_x", Some(Value::Float)),
    Field::new("RTV7", "prim_rot2_y", Some(Value::Float)),
    Field::new("RTV8", "prim_rot2_z", Some(Value::Float)),
    Field::new("SCOL", "side_color", Some(Value::Int)),
    Field::new("SIDS", "sides", Some(Value::Int)),
    Field::new("SIMG", "side_image", None),
    Field::new("STRE", "static_rendering", Some(Value::Bool)),
    Field::new("THRS", "threshold", Some(Value::Float)),
    Field::new("TVIS", "visible", Some(Value::Bool)),
    Field::new("U3DM", "use_mesh", Some(Value::Bool)),
    Field::new("VPOS", "position", Some(Value::Vector4)),
    Field::new("VSIZ", "size", Some(Value::Vector4)),
    Field::new("ZMSK", "use_depth_mask", Some(Value::Bool)),
];

/// eItemFlasher (item type 20)
pub(super) const ITEM_20: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("ADDB", "add_blend", Some(Value::Int)),
    Field::new("ALGN", "alignment", Some(Value::Int)),
    Field::new("BGLS", "desktop_backdrop", Some(Value::Bool)),
    Field::new("COLR", "color", Some(Value::Int)),
    Field::new("DSPT", "ui_show_texture", Some(Value::Bool)),
    Field::new("FALP", "alpha", Some(Value::Int)),
    Field::new("FHEI", "height", Some(Value::Float)),
    Field::new("FIAM", "filter_amount", Some(Value::Int)),
    Field::new("FILT", "filter_type", Some(Value::Int)),
    Field::new("FLAX", "flasher_x", None),
    Field::new("FLAY", "flasher_y", None),
    Field::new("FLDB", "depth_bias", Some(Value::Float)),
    Field::new("FROX", "rotation_x", Some(Value::Float)),
    Field::new("FROY", "rotation_y", Some(Value::Float)),
    Field::new("FROZ", "rotation_z", Some(Value::Float)),
    Field::new("FVIS", "visible", Some(Value::Bool)),
    Field::new("GAMB", "glass_ambient", Some(Value::Int)),
    Field::new("GBOT", "glass_pad_bottom", Some(Value::Float)),
    Field::new("GLFT", "glass_pad_left", Some(Value::Float)),
    Field::new("GRGH", "glass_roughness", Some(Value::Float)),
    Field::new("GRHT", "glass_pad_right", Some(Value::Float)),
    Field::new("GTOP", "glass_pad_top", Some(Value::Float)),
    Field::new("IDMD", "dmd", None),
    Field::new("IMAB", "image_b", Some(Value::String)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("LINK", "image_src_link", Some(Value::String)),
    Field::new("LMAP", "lightmap", Some(Value::String)),
    Field::new("MOVA", "modulate_vs_add", Some(Value::Float)),
    Field::new("RDMD", "render_mode", Some(Value::Int)),
    Field::new("RSTL", "render_style", Some(Value::Int)),
];

/// eItemRubber (item type 21)
pub(super) const ITEM_21: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("CLDR", "collidable", Some(Value::Bool)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("ESIE", "show_in_editor", Some(Value::Bool)),
    Field::new("ESTR", "static_rendering", Some(Value::Bool)),
    Field::new("HTEV", "hitEvent", Some(Value::Bool)),
    Field::new("HTHI", "hit_height", Some(Value::Float)),
    Field::new("HTTP", "height_top", Some(Value::Float)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MAPH", "physics_material", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("OVPH", "overwrite_physics", Some(Value::Bool)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RFCT", "friction", Some(Value::Float)),
    Field::new("ROTX", "rot_x", Some(Value::Float)),
    Field::new("ROTY", "rot_y", Some(Value::Float)),
    Field::new("ROTZ", "rot_z", Some(Value::Float)),
    Field::new("RSCT", "scatter", Some(Value::Float)),
    Field::new("RVIS", "visible", Some(Value::Bool)),
    Field::new("WDTP", "thickness", Some(Value::Int)),
];

/// eItemHitTarget (item type 22)
pub(super) const ITEM_22: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("CLDR", "collidable", Some(Value::Bool)),
    Field::new("DILB", "disable_lighting_below", Some(Value::Float)),
    Field::new("DILI", "disable_lighting_legacy", None),
    Field::new("DILT", "disable_lighting_top", Some(Value::Float)),
    Field::new("DRSP", "drop_speed", Some(Value::Float)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("HTEV", "hitEvent", Some(Value::Bool)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("ISDR", "is_dropped", Some(Value::Bool)),
    Field::new("LEMO", "legacy_mode", Some(Value::Bool)),
    Field::new("MAPH", "physics_material", Some(Value::String)),
    Field::new("MATR", "material", Some(Value::String)),
    Field::new("OVPH", "overwrite_physics", Some(Value::Bool)),
    Field::new("PIDB", "depth_bias", Some(Value::Float)),
    Field::new("RADE", "raise_delay", Some(Value::Int)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("RFCT", "friction", Some(Value::Float)),
    Field::new("ROTZ", "rot_z", Some(Value::Float)),
    Field::new("RSCT", "scatter", Some(Value::Float)),
    Field::new("THRS", "threshold", Some(Value::Float)),
    Field::new("TRTY", "target_type", Some(Value::Int)),
    Field::new("TVIS", "visible", Some(Value::Bool)),
    Field::new("VPOS", "position", Some(Value::Vector4)),
    Field::new("VSIZ", "size", Some(Value::Vector4)),
];

/// eItemBall (item type 23)
pub(super) const ITEM_23: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector3)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("BISC", "bulb_intensity_scale", Some(Value::Float)),
    Field::new("COLR", "color", Some(Value::Int)),
    Field::new("DCMD", "decal_mode", Some(Value::Bool)),
    Field::new("DIMG", "image_decal", Some(Value::String)),
    Field::new("FREF", "force_reflection", Some(Value::Bool)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("MASS", "mass", Some(Value::Float)),
    Field::new("PFRF", "playfield_reflection_strength", Some(Value::Float)),
    Field::new("RADI", "radius", Some(Value::Float)),
    Field::new("REEN", "reflection_enabled", Some(Value::Bool)),
    Field::new("SPHR", "pinball_env_spherical_mapping", Some(Value::Bool)),
];

/// eItemPartGroup (item type 24)
pub(super) const ITEM_24: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", Some(Value::Bool)),
    Field::new("TMIN", "timer_interval", Some(Value::Int)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", Some(Value::Int)),
    Field::new("LANR", "named_layer", Some(Value::String)),
    Field::new("GRUP", "part_group", Some(Value::String)),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("PMSK", "player_mode_visibility_mask", Some(Value::UInt)),
    Field::new("SPRF", "space_reference", Some(Value::Int)),
];

/// eItemTable
pub(super) const TABLE: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", None),
    Field::new("LVIS", "ui_visible", None),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
    Field::new("GRUP", "part_group", None),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("LEFT", "left", Some(Value::Float)),
    Field::new("TOPX", "top", Some(Value::Float)),
    Field::new("RGHT", "right", Some(Value::Float)),
    Field::new("BOTM", "bottom", Some(Value::Float)),
    Field::new(
        "EFSS",
        "is_fullsinglescreen_view_enabled",
        Some(Value::Bool),
    ),
    Field::new("VSM0", "desktop_view.mode", Some(Value::Int)),
    Field::new("ROTA", "desktop_view.rotation", Some(Value::Float)),
    Field::new("INCL", "desktop_view.inclination", Some(Value::Float)),
    Field::new("LAYB", "desktop_view.layback", Some(Value::Float)),
    Field::new("FOVX", "desktop_view.fov", Some(Value::Float)),
    Field::new("XLTX", "desktop_view.view_x", Some(Value::Float)),
    Field::new("XLTY", "desktop_view.view_y", Some(Value::Float)),
    Field::new("XLTZ", "desktop_view.view_z", Some(Value::Float)),
    Field::new("SCLX", "desktop_view.scale_x", Some(Value::Float)),
    Field::new("SCLY", "desktop_view.scale_y", Some(Value::Float)),
    Field::new("SCLZ", "desktop_view.scale_z", Some(Value::Float)),
    Field::new("HOF0", "desktop_view.horizontal_ofs", Some(Value::Float)),
    Field::new("VOF0", "desktop_view.vertical_ofs", Some(Value::Float)),
    Field::new("WTZ0", "desktop_view.window_top_z_ofs", Some(Value::Float)),
    Field::new("WBZ0", "desktop_view.window_bot_z_ofs", Some(Value::Float)),
    Field::new("VSM1", "cabinet_view.mode", Some(Value::Int)),
    Field::new("ROTF", "cabinet_view.rotation", Some(Value::Float)),
    Field::new("INCF", "cabinet_view.inclination", Some(Value::Float)),
    Field::new("LAYF", "cabinet_view.layback", Some(Value::Float)),
    Field::new("FOVF", "cabinet_view.fov", Some(Value::Float)),
    Field::new("XLFX", "cabinet_view.view_x", Some(Value::Float)),
    Field::new("XLFY", "cabinet_view.view_y", Some(Value::Float)),
    Field::new("XLFZ", "cabinet_view.view_z", Some(Value::Float)),
    Field::new("SCFX", "cabinet_view.scale_x", Some(Value::Float)),
    Field::new("SCFY", "cabinet_view.scale_y", Some(Value::Float)),
    Field::new("SCFZ", "cabinet_view.scale_z", Some(Value::Float)),
    Field::new("HOF1", "cabinet_view.horizontal_ofs", Some(Value::Float)),
    Field::new("VOF1", "cabinet_view.vertical_ofs", Some(Value::Float)),
    Field::new("WTZ1", "cabinet_view.window_top_z_ofs", Some(Value::Float)),
    Field::new("WBZ1", "cabinet_view.window_bot_z_ofs", Some(Value::Float)),
    Field::new("VSM2", "fullsinglescreen_view.mode", Some(Value::Int)),
    Field::new("ROFS", "fullsinglescreen_view.rotation", Some(Value::Float)),
    Field::new(
        "INFS",
        "fullsinglescreen_view.inclination",
        Some(Value::Float),
    ),
    Field::new("LAFS", "fullsinglescreen_view.layback", Some(Value::Float)),
    Field::new("FOFS", "fullsinglescreen_view.fov", Some(Value::Float)),
    Field::new("XLXS", "fullsinglescreen_view.view_x", Some(Value::Float)),
    Field::new("XLYS", "fullsinglescreen_view.view_y", Some(Value::Float)),
    Field::new("XLZS", "fullsinglescreen_view.view_z", Some(Value::Float)),
    Field::new("SCXS", "fullsinglescreen_view.scale_x", Some(Value::Float)),
    Field::new("SCYS", "fullsinglescreen_view.scale_y", Some(Value::Float)),
    Field::new("SCZS", "fullsinglescreen_view.scale_z", Some(Value::Float)),
    Field::new(
        "HOF2",
        "fullsinglescreen_view.horizontal_ofs",
        Some(Value::Float),
    ),
    Field::new(
        "VOF2",
        "fullsinglescreen_view.vertical_ofs",
        Some(Value::Float),
    ),
    Field::new(
        "WTZ2",
        "fullsinglescreen_view.window_top_z_ofs",
        Some(Value::Float),
    ),
    Field::new(
        "WBZ2",
        "fullsinglescreen_view.window_bot_z_ofs",
        Some(Value::Float),
    ),
    Field::new("ORRP", "override_physics", Some(Value::Int)),
    Field::new("ORPF", "override_physics_flipper", Some(Value::Bool)),
    Field::new("GAVT", "gravity", Some(Value::Float)),
    Field::new("FRCT", "friction", Some(Value::Float)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFA", "elasticity_falloff", Some(Value::Float)),
    Field::new("PFSC", "scatter", Some(Value::Float)),
    Field::new("SCAT", "default_scatter", Some(Value::Float)),
    Field::new("NDGT", "nudge_time", Some(Value::Float)),
    Field::new("PHML", "physics_max_loops", Some(Value::Int)),
    Field::new("REEL", "render_EM_reels", Some(Value::Bool)),
    Field::new("DECL", "render_decals", Some(Value::Bool)),
    Field::new("OFFX", "win_editor_view_offset_x", Some(Value::Float)),
    Field::new("OFFY", "win_editor_view_offset_y", Some(Value::Float)),
    Field::new("ZOOM", "win_editor_zoom", Some(Value::Float)),
    Field::new("SLPX", "angle_tilt_max", Some(Value::Float)),
    Field::new("SLOP", "angle_tilt_min", Some(Value::Float)),
    Field::new("BIMG", "backdrop_image_0", Some(Value::String)),
    Field::new("BIMF", "backdrop_image_1", Some(Value::String)),
    Field::new("BIMS", "backdrop_image_2", Some(Value::String)),
    Field::new("BIMN", "image_backdrop_night_day", Some(Value::Bool)),
    Field::new("IMCG", "image_color_grade", Some(Value::String)),
    Field::new("BLIM", "ball_image", Some(Value::String)),
    Field::new("BLSM", "ball_spherical_mapping", Some(Value::Bool)),
    Field::new("BLIF", "ball_image_decal", Some(Value::String)),
    Field::new("EIMG", "env_image", Some(Value::String)),
    Field::new("IMAG", "image", Some(Value::String)),
    Field::new("NOTX", "notes_text", Some(Value::String)),
    Field::new("SSHT", "screenshot", Some(Value::String)),
    Field::new("FBCK", "win_editor_backdrop", Some(Value::Bool)),
    Field::new("GLAS", "glass_top_height", Some(Value::Float)),
    Field::new("GLAB", "glass_bottom_height", Some(Value::Float)),
    Field::new("PLMA", "playfield_material", Some(Value::String)),
    Field::new("BCLR", "color_backdrop", Some(Value::Int)),
    Field::new("TDFT", "difficulty", Some(Value::Float)),
    Field::new("LZAM", "light_ambient", Some(Value::Int)),
    Field::new("LZDI", "light_emission", Some(Value::Int)),
    Field::new("LZHI", "light_height", Some(Value::Float)),
    Field::new("LZRA", "light_range", Some(Value::Float)),
    Field::new("LIES", "light_emission_scale", Some(Value::Float)),
    Field::new("ENES", "env_emission_scale", Some(Value::Float)),
    Field::new("GLES", "global_emission_scale", Some(Value::Float)),
    Field::new("AOSC", "AO_scale", Some(Value::Float)),
    Field::new("SSSC", "SSR_scale", Some(Value::Float)),
    Field::new("CLBH", "ground_to_lockbar_height", Some(Value::Float)),
    Field::new("SVOL", "table_sound_volume", Some(Value::Float)),
    Field::new("MVOL", "table_music_volume", Some(Value::Float)),
    Field::new("PLST", "playfield_reflection_strength", Some(Value::Int)),
    Field::new("BDMO", "ball_decal_mode", Some(Value::Bool)),
    Field::new(
        "BPRS",
        "ball_playfield_reflection_strength",
        Some(Value::Float),
    ),
    Field::new(
        "DBIS",
        "default_bulb_intensity_scale_on_ball",
        Some(Value::Float),
    ),
    Field::new("GDAC", "ui_editor_grid", Some(Value::Bool)),
    Field::new("UAOC", "enable_AO", Some(Value::Int)),
    Field::new("USSR", "enable_SSR", Some(Value::Int)),
    Field::new("TMAP", "tonemapper", Some(Value::Int)),
    Field::new("EXPO", "exposure", Some(Value::Float)),
    Field::new("BLST", "bloom_strength", Some(Value::Float)),
    Field::new("MATR", "materials", Some(Value::Objects(Node::Material))),
    Field::new(
        "RPRB",
        "renderprobes",
        Some(Value::Objects(Node::RenderProbe)),
    ),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("CODE", "vbs_script", Some(Value::Script)),
    Field::new("CCUS", "ui_custom_colors", Some(Value::Raw)),
    Field::new("TLCK", "tablelocked", Some(Value::Int)),
];

/// eItemCollection
pub(super) const COLLECTION: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", None),
    Field::new("LVIS", "ui_visible", None),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
    Field::new("GRUP", "part_group", None),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("NAME", "name", Some(Value::WideString)),
    Field::new("ITEM", "parts", Some(Value::WideString)),
    Field::new("EVNT", "fire_events", Some(Value::Bool)),
    Field::new("SSNG", "stop_single_events", Some(Value::Bool)),
    Field::new("GREL", "group_elements", Some(Value::Bool)),
];

/// JSONSerializer::kMaterialNode
pub(super) const MATERIAL: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::String)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", None),
    Field::new("LVIS", "ui_visible", None),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
    Field::new("GRUP", "part_group", None),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("TYPE", "type", Some(Value::Int)),
    Field::new("NAME", "name", Some(Value::String)),
    Field::new("WLIG", "wrap_lighting", Some(Value::Float)),
    Field::new("ROUG", "roughness", Some(Value::Float)),
    Field::new("GIML", "glossy_image_lerp", Some(Value::Float)),
    Field::new("THCK", "thickness", Some(Value::Float)),
    Field::new("EDGE", "edge", Some(Value::Float)),
    Field::new("EALP", "edge_alpha", Some(Value::Float)),
    Field::new("OPAC", "opacity", Some(Value::Float)),
    Field::new("BASE", "base_color", Some(Value::Int)),
    Field::new("GLOS", "glossy_color", Some(Value::Int)),
    Field::new("COAT", "clearcoat_color", Some(Value::Int)),
    Field::new("RTNT", "refraction_tint", Some(Value::Int)),
    Field::new("EOPA", "is_opacity_active", Some(Value::Bool)),
    Field::new("ELAS", "elasticity", Some(Value::Float)),
    Field::new("ELFO", "elasticity_falloff", Some(Value::Float)),
    Field::new("FRIC", "friction", Some(Value::Float)),
    Field::new("SCAT", "scatter_angle", Some(Value::Float)),
];

/// JSONSerializer::kRenderProbeNode
pub(super) const RENDER_PROBE: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", Some(Value::String)),
    Field::new("VCEN", "center", None),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", None),
    Field::new("LVIS", "ui_visible", None),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
    Field::new("GRUP", "part_group", None),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("TYPE", "type", Some(Value::Int)),
    Field::new("NAME", "name", Some(Value::String)),
    Field::new("RBAS", "roughness", Some(Value::Int)),
    Field::new("RPLA", "reflection_plane", Some(Value::Raw)),
    Field::new("RMOD", "reflection_mode", Some(Value::Int)),
    Field::new("RLMP", "disable_light_reflection", Some(Value::Bool)),
];

/// JSONSerializer::kDragPointNode
pub(super) const DRAG_POINT: &[Field] = &[
    Field::new("PIID", "id", None),
    Field::new("NAME", "name", None),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("TMON", "timer_enabled", None),
    Field::new("TMIN", "timer_interval", None),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
    Field::new("GRUP", "part_group", None),
    Field::new("PNTS", "dragpoints", None),
    Field::new("DPNT", "dragpoints", Some(Value::Objects(Node::DragPoint))),
    Field::new("VCEN", "center", Some(Value::Vector2)),
    Field::new("POSZ", "position_z", Some(Value::Float)),
    Field::new("SMTH", "smooth", Some(Value::Bool)),
    Field::new("SLNG", "slingshot", Some(Value::Bool)),
    Field::new("ATEX", "auto_texture", Some(Value::Bool)),
    Field::new("TEXC", "texture_coordinate", Some(Value::Float)),
    Field::new("LOCK", "ui_locked", Some(Value::Bool)),
    Field::new("LVIS", "ui_visible", Some(Value::Bool)),
    Field::new("LAYR", "legacy_layer", None),
    Field::new("LANR", "named_layer", None),
];

/// Fields made of repeated records, collected in an array
pub(super) const COLLECTION_REPEATABLE: &[&str] = &["ITEM"];

/// The field tables of the parts, by vpinball item type
pub(super) fn part_fields(item_type: u32) -> Option<&'static [Field]> {
    match item_type {
        0 => Some(ITEM_0),
        1 => Some(ITEM_1),
        2 => Some(ITEM_2),
        3 => Some(ITEM_3),
        4 => Some(ITEM_4),
        5 => Some(ITEM_5),
        6 => Some(ITEM_6),
        7 => Some(ITEM_7),
        8 => Some(ITEM_8),
        9 => Some(ITEM_9),
        10 => Some(ITEM_10),
        11 => Some(ITEM_11),
        12 => Some(ITEM_12),
        17 => Some(ITEM_17),
        18 => Some(ITEM_18),
        19 => Some(ITEM_19),
        20 => Some(ITEM_20),
        21 => Some(ITEM_21),
        22 => Some(ITEM_22),
        23 => Some(ITEM_23),
        24 => Some(ITEM_24),
        _ => None,
    }
}
